### ISSUE TITLE
Thank you! Thank you! Thank you!

### ISSUE THREAD

**Issue by haizaar** [spacewander/openresty-vim#1]
Thank you very much for creating this plugin!
It makes life so much prettier!

(Didn't find other way to contact you, hence the deleted issue)

**Comment by spacewander** [comment]
@haizaar 
Would you mind staring this repo? :smiley:

**Comment by haizaar** [comment]
Done!

**Comment by haizaar** [comment]
Btw, you can announce it on openresty mailing list: https://groups.google.com/forum/#!forum/openresty-en
